### ISSUE TITLE
SPA-010 / SPA-011 assert exception - demo missions broken

### ISSUE THREAD

**Issue by Igneous01** [FlightControl-Master/MOOSE_MISSIONS#9]
When I start up any of these demo missions (I add Game Master / Tactical CMD so I can look around with camera) I get the following errors - they happen each time i run the missions. I am running the latest stable release of DCS 1.5

![image](https://cloud.githubusercontent.com/assets/5571589/25069238/5e361bba-2249-11e7-9715-7df79b117433.png)

![image](https://cloud.githubusercontent.com/assets/5571589/25069242/710e1008-2249-11e7-99a1-d47fa846e778.png)

**Comment by FlightControl-Master** [comment]
Hi @Igneous01 ! 

You're looking at the wrong place :-) 

We follow now a **release process** during the creation of the framework.

The correct location for you to look is in the branch master-release: 
https://github.com/FlightControl-Master/MOOSE/tree/master-release

The place where you were looking (master), is for beta testers, and there the missions load the MOOSE framework **dynamically**, that is, it is loaded with the latest features not in release 2.0.

The versions in the branch master-release are **statically** loaded, that means, with the MOOSE release 2.0, and missions can just be started without any additional setups.

If you wanna join our community on slack, please send me an email to flightcontrol_moose@outlook.com.

I suggest you do that, because it will bring you interactive Q&A and join the collaborative community of users of the framework. Once i receive your email, i can join you up on the moose support at slack.com.

Sven
